---
github_username: karubits
timezone: Asia/Tokyo
ntp_server_1: ntp.nict.jp
ntp_server_2: pool.ntp.org
ntp_fallback_1: time-a-g.nist.gov
ntp_fallback_2: time.cloudflare.com
ntp_fallback_3: asia.pool.ntp.org
ssh_port: 4022
root_ps1: PS1="[\[$(tput sgr0)\]\[\033[38;5;160m\]\u\[$(tput sgr0)\]@\[$(tput sgr0)\]\[\033[38;5;10m\]\h\[$(tput sgr0)\]:\[$(tput sgr0)\]\[\033[38;5;14m\]\w\[$(tput sgr0)\]]\\$ \[$(tput sgr0)\]"

