---
- name: Restart sshd
  service:
    name: ssh
    state: restarted

- name: Restart syslog service
  service:
    name: rsyslog
    state: restarted

- name: Restart cron service
  service:
    name: cron
    state: restarted

- name: Restart timesyncd
  service:
    name: systemd-timesyncd
    state: restarted

- name: Restart qemu-guest-agent
  service:
    name: qemu-guest-agent
    state: restarted
